name = "Ratios"
uuid = "c84ed2f1-dad5-54f0-aa8e-dbefe2724439"
authors = ["Tim Holy <tim.holy@gmail.com>"]
version = "0.4.0"

[compat]
julia = "0.7, 1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
